chore: crypto-ffi: fix typedoc warning
This fixes the following:

  error TS2345: Argument of type 'Buffer<ArrayBufferLike>' is not assignable
  to parameter of type 'BufferSource'.

(cherry picked from commit bb040ff111a1c5d1c65d781eec858a390a899d6a)