fix: publishing android artifact by disabling javadoc generation
Since we moved the generated uniffi code into separate library (uniffi-android)
the Dokka javadoc generation fails with:

java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9

Since we haven't found a solution for this bug we are disabling javadoc generation
for the time being.